# Configuración Base - Worker
database:
  postgres:
    host: "localhost"
    port: 5432
    database: "edugo"
    user: "edugo_user"
    max_connections: 10
    ssl_mode: "disable"
  
  mongodb:
    database: "edugo"
    timeout: 10s

messaging:
  rabbitmq:
    queues:
      material_uploaded: "edugo.material.uploaded"
      assessment_attempt: "edugo.assessment.attempt"
    exchanges:
      materials: "edugo.materials"
    prefetch_count: 5

nlp:
  provider: "openai"
  model: "gpt-4"
  max_tokens: 4000
  temperature: 0.7

logging:
  level: "info"
  format: "json"
