# Configuración Base - API Administración
server:
  port: 8081
  host: "0.0.0.0"
  read_timeout: 30s
  write_timeout: 30s

database:
  postgres:
    host: "localhost"
    port: 5432
    database: "edugo"
    user: "edugo_user"
    max_connections: 25
    ssl_mode: "disable"
  
  mongodb:
    database: "edugo"
    timeout: 10s

logging:
  level: "info"
  format: "json"
